language: cpp

compiler:
    - clang
    - g++ 

os:
    - linux
    - os

sources: 
    - ubuntu-toolchain-r-test
  
packages:
    - g++-7

script:
    - cd Word-Flow
    - qmake -project "CONFIG += qtestlib"
    - qmake Word-Flow.pro
    - make
    - cd bin
    - ./Word-Flow
    - cat testing.log



