language: cpp

compiler:
    - clang
    - g++ 
    -std= c++11

os:
    - linux
    - os

script:
    - qmake -project "CONFIG += qtestlib"
    - qmake Word-Flow/Word-Flow.pro
    - make
    - cd build



