language: cpp

compiler:
    - clang
    - g++ -std= c++11

os:
    - linux
    - os

before_install:
    - sudo apt-get update
    - sudo apt-get install -y libxm12-dev

script:
    - qmake -project "CONFIG += qtestlib"
    - qmake Word-Flow/Word-Flow.pro
    - make
    - cd build



